### ISSUE TITLE
Ordering issues in SDP

### ISSUE THREAD

**Issue by hendrikhofstadt** [pion/webrtc#1058]
I was just about to report #1055 when I saw that @Sean-Der just fixed the issue.

However there are a couple of cases where this does not work:

1. When the browser creates the first offer, it might not put data first and the answer would break the ordering.
2. When the browser creates the first offer without data, any subsequent offer by the library will break the ordering.
2. When the browser creates the first offer without a data channel, previously this library would answer with no data channel. When renegotiating however (offer from this library), we would always add a data channel even though that's an *unexpected side-effect*. If it's not an unexpected side-effect and we always want a data channel, the system would be in an *unexpected state* if the browser initiated the session.

**Comment by Sean-Der** [comment]
@hendrikhofstadt Oof I didn't think about these at all. Currently the `createOffer` generation doesn't take into account the remote SDP at all.

Let me rework everything and come back to you. Would you be up for helping me write tests cases? You don't have to write any code, but I don't do any re-negotation myself in anything I built so am ignorant to all the things I need to handle :/

**Comment by hendrikhofstadt** [comment]
Thanks a lot for working on this. 

I really appreciate the work you've done. This is an amazing piece of software, especially considering that there's little to no reference code / good doc out there beyond the official implementation.

I'd be happy to help you with test cases. Just ping me once you've done some initial refactoring.

**Comment by Sean-Der** [comment]
Thank you so much @hendrikhofstadt really appreciate the positivity! I feel really luck to work on this stuff, having people use it is very motivating and gives me a lot of purpose :) It is fun building stuff that people want.

Would you mind checking out https://github.com/pion/webrtc/pull/1065 ? I may have missed issues, but it covers the following (I believe)

1.) When answering we always try the match the order of the offer.
2.) When re-offering we now always match the order of the other side (instead of just deserializing our local state without any concern for the other side)
3.) Should be fixed as well! We only offer a DataChannel the first time, otherwise we always try to match the remote.
