### ISSUE TITLE
Add lint to TODO/FIXME

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#106]
Require that each comment with a TODO/FIXME has an associated github issue (otherwise we will lose track of them)

**Comment by trivigy** [comment]
@Sean-Der can we lose some of the restrictions here? Personally I use TODO and FIXME a lot during "work in progress" to indicate things that I put in place but still require additional coding. Those are not stories within themselves. I fear is that this kind of strict linting is discouraging me from putting indications of things that don't fully work by requiring me to have to open tens of issues for things people are unlikely to actually be able to help with.

One proposal is maybe adding additional marker like "ISSUE" or maybe doing this sort of linting only on the TODO since that one is a bit more like: "Here is another thing that needs to be completed."

**Comment by maxhawkins** [comment]
We should definitely do this. I just had the idea to add this and found you had already thought of it.

**Comment by enobufs** [comment]
@Sean-Der 
I checked the current state of max data channel message size.
As of today, our implementation allows up to 65536 bytes, or math.MaxUint16
RFC for WebRTC `https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13` states:
```
   The SCTP base protocol specified in [RFC4960] does not support the
   interleaving of user messages.  Therefore sending a large user
   message can monopolize the SCTP association.  To overcome this
   limitation, [I-D.ietf-tsvwg-sctp-ndata] defines an extension to
   support message interleaving, which SHOULD be used.  As long as
   message interleaving is not supported, the sender SHOULD limit the
   maximum message size to 16 KB to avoid monopolization.
``` 
so, 16KB is recommended. Since it is not a `MUST`, I guess we are ok.
Next gen SDP draft specifies an attribute, `a=max-message-size`, but I don't think it is used in WebRTC.

Therefore, you can remove all these params (and the helper method) all together in sctptransport.go:
```
remoteMaxMessageSize
canSendSize
r.maxMessageSize
calcMessageSize()
```

Can you do that in this branch?
