### ISSUE TITLE
Document which public interfaces aren't connected

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#107]
We have implement a lot of the ECMAScript WebRTC API, but things aren't connected.

Users may find this confusing, we should document/annotate things that aren't connected yet so we can make a plan around it.

**Comment by gedw99** [comment]
Great. If you can do basic document then it will make it much easier to get
it working with flutter webrtc client.

**Comment by trivigy** [comment]
Agreed. We could potentially use https://blog.golang.org/godoc-documenting-go-code (`BUG(r):`) for now to indicate that. I think there are generally a lot of minor API transformations that are happening because the library is missing a lot of functionalities related to rfc compliance. At least on my end I am adding some of those as fast as I can but in the process I end up introducing public APIs that are not fully complete yet.

Any suggestions of a good process are highly welcome on my end so I could follow those.

**Comment by Sean-Der** [comment]
I don't have any plans for doing this. It is pretty subjective/open ended so hard to really do.

What we can/should is write tests that target WASM/Go and ensure we match the API. This already exists in the WASM covering ticket, so we can just keep moving forward with that!
