### ISSUE TITLE
Streaming to latest Safari and Firefox on OSX.

### ISSUE THREAD

**Issue by ababo** [pion/webrtc#1076]
The `gstreamer-send` example doesn't work with latest Safari and Firefox. Indeed, there's no video on Safari and both video and audio on Firefox. Running on OSX 10.15.3.

**Comment by mlgarrido** [comment]
Same problem here. Working on chrome -> chrome, firefox -> chrome, safari -> chrome, but never play on safari or firefox. Working on Android mobile too, but same problem on ios (chrome or safari).

**Comment by Esser420** [comment]
Funny because h264 video only works on firefox and safari but not chrome :(

**Comment by danj565** [comment]
The broadcast example also only seems to work in Chrome and no other browsers.  I get a blank video with the below error in Firebox with the out of the box broadcast example.  Is this an issue with browser support, immature protocol, or an issue with the library/examples?

InvalidStateError: Cannot set remote answer in state stable

**Comment by josharian** [comment]
Ditto here: The reflect example on macOS only works on Chrome. Firefox silently shows nothing. Safari says: `TypeError: pc.addStream is not a function. (In 'pc.addStream(stream)', 'pc.addStream' is undefined)`.

**Comment by Sean-Der** [comment]
There are a lot of different variables at play here

* `gstreamer-send` probably doesn't work with Safari because we hardcode the PayloadType and/or you don't have a version that supports VP8 yet. Can you try adding [`getPayloadType`](https://github.com/pion/webrtc/blob/master/examples/play-from-disk/main.go#L200-L203), we should add this `pion/webrtc` itself maybe.

* `pc.addStream` is because Safari doesn't include the deprecated WebRTC APIs. Instead of `addStream` we should call `addTrack` and loop over all the `MediaStreamTrack` members in the `MediaStream`


* `InvalidStateError: Cannot set remote answer in state stable` I am not sure what is happening, `Start Session` multiple times maybe? I just checked and FireFox does work with broadcast for me!

**Comment by greko6** [comment]
I do feel like this issue might be related to https://github.com/pion/ion-sfu/issues/23

Basically, m= for video track in the SDP Answer is most likely hardcoded to UDP/TLS/RTP/SAVPF 96. For Chrome, 96 means VP8/90000. However, for anything based on IOS, 96 actually means h264. 

This also explains why h264 works perfectly fine between Safari and Chrome on Mac, but not with VP8. 

For Safari and Chrome on MacOS, to make it work, SDP Answer has to be UDP/TLS/RTP/SAVPF 100 for VP8. 96 is reserved for h264.

Hope it makes sense.

**Comment by MrDell61** [comment]
can use h254 with `profile-level-id=42e01f`? it looks like it works

**Comment by Sean-Der** [comment]
This is fixed by 7edfb701e09e89258d4b3235cded99befc8058fd :partying_face: 

pion/webrtc internally now is aware of PayloadTypes, and when answering sets the proper values. When you create a track you instead only are aware of MimeType+Format Parameters. `example-webrtc-applications` will be updated when `v3.0.0` is released.

`examples/broadcast` can be used to day and I was able to do `Chrome` and view in `Chrome, Safari and FireFox`
