### ISSUE TITLE
RTX support

### ISSUE THREAD

**Issue by adwpc** [pion/webrtc#1083]
## Summary
I think `RTX` feature cat fix this bug:
#1081 

## Motivation

webrtc use rtx to send packet when it receive nack.
rtx use different ssrc and payload type
It make bandwidth and lost packet rate calculation more precisely.

**Comment by longsleep** [comment]
Like shown in #1081 `ssrc-group:FID` (RTX) SDP lines are currently not handled and thus the extra RTX `ssrc` entries are treated incorrectly as a track in https://github.com/pion/webrtc/blob/master/sdp.go#L23-L56

Since an not existing extra track is returned, this leads to an wrongly started RTPReceiver if the order of all tracks in the SDP is so that a receiver for the wrong kind gets skipped earlier.

This problem causes warnings like `Incoming unhandled RTCP ssrc(3691602899), OnTrack will not be fired` since the RTCReceiver for the ssrc of the ssrc-group was started and then no other RTCReceiver is available for the track data.

Workaround is to remove the `ssrc-group` and its associated extra `ssrc-*` lines before setting the remote description.

**Comment by Sean-Der** [comment]
Hey @adwpc 

I am tracking all media issues in https://github.com/pion/webrtc/projects/17 if you get a chance give it a look and make sure I am not missing anything! My goals is to get most of this done by mid July.

thanks :)
