### ISSUE TITLE
Transceiver Mid test failing

### ISSUE THREAD

**Issue by jeremija** [pion/webrtc#1186]
### Your environment.
  - Version: 4f362ee

### Steps to reproduce

```
$ go test ./ -run Transceiver_Mid -v -race -count=10
```

### Log

```
=== RUN   TestPeerConnection_Transceiver_Mid
==================
WARNING: DATA RACE
Read at 0x00c00037c410 by goroutine 70:
  github.com/pion/webrtc/v2.(*PeerConnection).startRTPSenders()
      /pion/webrtc/peerconnection.go:973 +0x149
  github.com/pion/webrtc/v2.(*PeerConnection).startRenegotation.func1()
      /pion/webrtc/peerconnection.go:1724 +0x9bc

Previous write at 0x00c00037c410 by goroutine 102:
  github.com/pion/webrtc/v2.(*RTPTransceiver).setSendingTrack()
      /pion/webrtc/rtptransceiver.go:96 +0x7a
  github.com/pion/webrtc/v2.(*PeerConnection).AddTrack()
      /pion/webrtc/peerconnection.go:1196 +0x20c
  github.com/pion/webrtc/v2.TestPeerConnection_Transceiver_Mid()
      /pion/webrtc/peerconnection_renegotation_test.go:297 +0xfa5
  testing.tRunner()
      /usr/local/go/1.14/libexec/src/testing/testing.go:992 +0x1eb

Goroutine 70 (running) created at:
  github.com/pion/webrtc/v2.(*PeerConnection).startRenegotation()
      /pion/webrtc/peerconnection.go:1691 +0x7e
  github.com/pion/webrtc/v2.(*PeerConnection).SetRemoteDescription()
      /pion/webrtc/peerconnection.go:822 +0xb6b
  github.com/pion/webrtc/v2.TestPeerConnection_Transceiver_Mid()
      /pion/webrtc/peerconnection_renegotation_test.go:292 +0xe66
  testing.tRunner()
      /usr/local/go/1.14/libexec/src/testing/testing.go:992 +0x1eb

Goroutine 102 (running) created at:
  testing.(*T).Run()
      /usr/local/go/1.14/libexec/src/testing/testing.go:1043 +0x660
  testing.runTests.func1()
      /usr/local/go/1.14/libexec/src/testing/testing.go:1285 +0xa6
  testing.tRunner()
      /usr/local/go/1.14/libexec/src/testing/testing.go:992 +0x1eb
  testing.runTests()
      /usr/local/go/1.14/libexec/src/testing/testing.go:1283 +0x527
  testing.(*M).Run()
      /usr/local/go/1.14/libexec/src/testing/testing.go:1200 +0x2ff
  main.main()
      _testmain.go:338 +0x223
==================
    TestPeerConnection_Transceiver_Mid: testing.go:906: race detected during execution of test
--- FAIL: TestPeerConnection_Transceiver_Mid (0.43s)
    : testing.go:906: race detected during execution of test
```

**Comment by jeremija** [comment]
Unable to reproduce after #1170 was merged.

**Comment by sgotti** [comment]
@jeremija It should be fixed by #1170 since we skip starting a not negotiated sender. But the test should wait for negotiation to be finished before continuing on another negotiation. A possible solution is the one used in `TestPeerConnection_Start_Right_Receiver`:

```
	pcOffer.negotiationLock.Lock()
	pcAnswer.negotiationLock.Lock()
	pcOffer.negotiationLock.Unlock()
	pcAnswer.negotiationLock.Unlock()
```

Basically wait for negotiation to be completed before trying another negotiation.

This is related to a broader issue I'd like to open on defining/improving or documenting how pion/webrtc is resistant to concurrent calls. Currently there could be various issues if some peerConnection functions like the negotiation ones are concurrently called and I'm avoiding this by serializing calls to the peerConnection on the caller side. But this behavior should be changed or documented .

**Comment by jeremija** [comment]
That's why I figured so I closed the issue. I restarted the test on your PR and it passed.

I can still create a PR with the negotiationLock.

It would be awesome if we could make pion more thread-safe so I won't have to resort to things like this: https://github.com/peer-calls/peer-calls/blob/4698405bf049e3293bece9375d9b3a763b9b6249/server/wrtcnegotiator.go#L84-L87

**Comment by sgotti** [comment]
> It would be awesome if we could make pion more thread-safe so we won't have to resort to workarounds like this: https://github.com/peer-calls/peer-calls/blob/4698405bf049e3293bece9375d9b3a763b9b6249/server/wrtcnegotiator.go#L84-L87

I think we should open a dedicated issue since there're different point in the code not really thread safe. Regarding the negotiation calls that needs synchronization this is also more complex since it shouldn't be permitted to call them in the wrong order (I remember that the webrtc specs should define how to handle such kind of states).
