### ISSUE TITLE
Massive amounts of garbage (short-lived allocations)

### ISSUE THREAD

**Issue by jech** [pion/webrtc#1227]
Here are some results from memory profiling of Pion as used by my SFU.  I'll probably get around to fixing the issues at some point, but I'm submitting this report in case somebody wants to get their hands dirty.

The bad news is that Pion generates massive amounts of garbage.  The good news is that in the particular case of my SFU this only happens in a few places, and should therefore be easy to fix.

# crypto/cipher.NewCTR

This accounts for one third of the allocations.  The call chain is

    (*RTPSender).SendRTP -> (*WriteStreamSRTP).WriteRTP -> (*SessionSRTP).writeRTP -> (*Context).encryptRTP -> NewCTR
    
Since `crypto/cipher.Stream` doesn't have a `Reset` method, I'm not quite sure how to fix that.  It might require a change to the Go crypto library.

# github.com/pion/srtp.growBufferSize

This accounts for slightly less than one third of the allocations.  The call chain is exactly the same as in case 1 above.

My hunch is that dynamically growing the buffer size is a bad idea here: a pool of maximum-size buffers should be allocated, and buffers should be reused whenever possible.

# github.com/pion/transport/packetio.(*Buffer).Write

This accounts for one sixth of the allocations.  The guilty bit is at line 45:

          .          .     43:func (b *Buffer) Write(packet []byte) (n int, err error) {
          .          .     44:   // Copy the packet before adding it.
    59.56MB    59.56MB     45:   packet = append([]byte{}, packet...)
          .          .     46:
          .          .     47:   b.mutex.Lock()
          
The call chain is

    (*SessionSRTP).decrypt -> (*ReadStreamSRTP).write -> (*Buffer).Write

There are other issues, such as the samplebuilder requiring an allocation on each packet, but these are less relevant for my use case.

**Comment by Sean-Der** [comment]
@jech Don't think it will help allocations, but Chrome recently turned on AES-GCM support! It should be easy enough to add to `pion/srtp`, I made sure it wouldn't be a breaking change. If you have AES-NI should be a significant performance improvement. 

-----

It is probably worth digging into  `packetio.Buffer`, and how we can improve it!
* allows us to do non-blocking writes into the next subsystem `ICE -> DTLS` etc.. by queuing
* allows that queue to drop packets if it overfills 
* gives us thread safety between components. I think a lot of overhead comes into Pion because made every subsystem a unique package. We made everything thread safe at the boundaries, and causes issues. I am not sure what the answer is.

**Comment by jech** [comment]
Why is there extra buffering between the layers?  Why aren't the writes synchronous?

**Comment by Sean-Der** [comment]
A user might not be calling `Read` fast enough, this avoids packet loss during those cases.

It would be nice if we could pass single buffer via Read and then each step of the way uses it in place `(User) -> SRTP -> ICE`!

**Comment by jech** [comment]
The `packetio.Buffer` issue is hopefully fixed by https://github.com/pion/transport/pull/72

**Comment by jech** [comment]
The `NewCTR` issue is hopefully fixed by https://github.com/pion/srtp/pull/76

**Comment by jech** [comment]
The `growBuffer` issue is hopefully fixed by https://github.com/pion/srtp/pull/77.  I'm closing this issue, please reopen if you disagree.
