### ISSUE TITLE
tracing id 

### ISSUE THREAD

**Issue by newzai** [pion/webrtc#1250]
in SFU server, has mary peerconnection object.  now how to discriminate each pc by log is very difficulty。 so I a tracing id to identifying each pc，ice agent , ice address(relay,host) , dtls....

**Comment by Sean-Der** [comment]
Hey @newzai 

The W3C decided against this, so we aren't planning to do it either. You can see the thread [here](https://github.com/w3c/webrtc-pc/issues/1775). We try to keep in sync so that our WASM bindings make sense as well.

I would embed the PeerConnection in another struct and keep the ID there.

Thanks for using Pion!

**Comment by jinleileiking** [comment]
any progress?
