### ISSUE TITLE
No easy way to restart ICE

### ISSUE THREAD

**Issue by jech** [pion/webrtc#1251]
At peerconnection.c:406, it says:
```
	case options != nil:
		return SessionDescription{}, fmt.Errorf("TODO handle options")
```
I don't see any other way to restart ICE on an existing PC.  (I'm currently working around the issue by tearing down the connection and creating a new one, but that has other problems, such as requiring a keyframe even if the interruption was short-lived.)

**Comment by Sean-Der** [comment]
Yea we really need to do this.

https://github.com/pion/ice/issues/190 was filed, but I never made any progress on it. I really don't think it will be that difficult either. 

Will keep you updated, but my guess is ~4 days of work so I think I can make this happen within the month!

**Comment by Sean-Der** [comment]
@jech `pion/ice` supports restarts!

This will be the first feature in the `/v3` branch, we have to make breaking API changes to support this unfortunately. 

* we never went to `ConnectionStateFailed` (only Disconnected). 
* We also would go to `Disconnected` after 30 seconds (instead of the correct 5 seconds)

In the next few days I hope to have this resolved, and you can use a `/v3` version of pion/webrtc. There will be some API breakage for the next few weeks, but I hope to finish everything by mid July.

thanks!
