### ISSUE TITLE
Include Features Matrix

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#1279]
Lots of users ask in Slack what we support (and what we plan on supporting)

We should throw a simple `FEATURES.md` in the repo.

**Comment by ashellunts** [comment]
I can do this but need help to figure out actually what is supported.

**Comment by Sean-Der** [comment]
@ashellunts :fire: that would be awesome! I was kind of blocked on finding a good layout/design in the README. If it is too long it will not be as approachable. Maybe we can remove `webassembly` and make it in entry

These are the sections I see.

* Pure Go
  - No C dependencies

* PeerConnection API
    - Renegotiation
    - Full ICE Agent
    - ICE Restart
    - Trickle ICE
    - ICE-TCP
    - STUN
    - TURN (UDP, TCP, DTLS and TLS)
    - Plan-B and Unified Plan
    - mDNS Candidates

* DataChannels
   - Ordered/Unordered
   - Lossy/Lossless

* Media
   - API with direct RTP/RTCP access
   - Opus, PCM, H264, VP8 and VP9 packetizers
   - Readers/Writers to pull from disk
   - Easy integration with x264, libvpx, GStreamer and ffmpeg for encode and decode.
   - Simulcast

* Platform Support
    - Desktop (Windows and Mac)
    - Servers (Linux and FreeBSD)
    - Mobile (Android and iOS)
    - Web (Webassembly)

**Comment by scorpionknifes** [comment]
Here is a quick draft for a FEATURES.md. https://gist.github.com/scorpionknifes/5627ff9cc23aca76129191aa03b7f463.

Representing data using a matrix/table seems counter-intuitive unless we want to compare pion to something else (features). e.g

| | Example | Example  |
| --------: | :-------- | :-------- |
| Example | 👍 | ⛔️|

I was also thinking of using ticks e.g
- [x] Example
- [ ] Example

Let me know if there are any other ideas for design

**Comment by Sean-Der** [comment]
@scorpionknifes That's a good point! There are a few other states I am not sure how to represent.

* This feature is missing, but we we will do it eventually
* This feature is missing, but we will not be implementing
* This feature is missing, but you can accomplish it yourself  (and we may do it in the future as well)

**Comment by tekig** [comment]
Many complex terms can scare people off or raise their expectations. They may say "A lot has been done here, we can easily use this project", but they are not.

I think that people who understand will not switch to another project, because they already have a ready-made solution that works. Not sure, but people come here who don't know much about WebRTC in the beginning. The words ICE, TURN and etc wouldn't give me anything. I wanted to see an example that works and is simple so that a quick start can be done.

I think at the beginning you need to put a quick start, only then the features. An example should implement the most popular usecase, and also offer examples for less popular usecase. These examples should work in the real world so that the user does not think they have been fooled.

Sorry a little off topic.
