### ISSUE TITLE
Unhandle SSRC Error

### ISSUE THREAD

**Issue by DevRockstarZ** [pion/webrtc#1305]
My environment is GCP EC2 / Debian 10.

I run EC2's pion to connect with my local PC,

It change offer and answer both, But error occurs.

pc ERROR: 2020/07/10 02:32:38 Incoming unhandled RTP ssrc(2306978415)
pc ERROR: 2020/07/10 02:32:41 Incoming unhandled RTCP ssrc(2306978415)

How can I handle this error? Thanks.

**Comment by Sean-Der** [comment]
@DevRockstarZ This happens when Pion sees a video track the remote hasn't offered yet. This can happen (and isn't fatal) during re-negotation if you start sending video before exchanging SDPs. After exchanging the SDP this would be resolved. Are you seeing any bad behavior here, or just this message?

What version of Pion are you using. Does this error happen from using one of our `examples`? What are the two WebRTC Agents? `Pion <-> Pion` or `Chrome <-> Pion` etc...

**Comment by DevRockstarZ** [comment]
@Sean-Der Thank you for your reply. I'm making audio - SFU pion server.
Several Clients(Pion) createOffer to Pion SFU server.
And Pion SFU server createAnswer to Clients.
When another Client createOffer to Pion SFU server, re-negotiation will be occur.
I'll check my code and fix when re-negotiation fails.
Thanks for your reply again! Have a nice day!

**Comment by DevRockstarZ** [comment]
@Sean-Der I'm really sorry for asking question again, but I logged my pion-SFU,
--- Server Side (LINUX, Pion) Log ---
I WILL SEND OFFER..!!
2020/07/13 04:42:43 user 1594615360898785951: handle event answer (comes from client)
-> pc ERROR: 2020/07/13 04:42:43 Incoming unhandled RTP ssrc(939579869)
-> pc ERROR: 2020/07/13 04:42:46 Incoming unhandled RTCP ssrc(939579869)
I think when I handle answer, pc.SetRemoteDescription() function goes wrong.
How can I solve this problem?
When I run server on my local PC, it looks fine.
But, when I run server on linux it goes fail.
Thanks!
