### ISSUE TITLE
Return value of Track.Write()

### ISSUE THREAD

**Issue by jech** [pion/webrtc#1387]
Commit 6cca2786c9f46f5c22d1baf3433b1102fbaa24b7 by @s4y fixed error handling in `Track.Write`.  The new behaviour is better, but I've got a problem with the return value.

The function now returns an error value if any of the writes have failed.  I don't see how I can use this value, since it is only correct to resend the packet if *all* writes have failed.  Thus, I suggest changing the behaviour to return `nil` if any of the writes have succeded.  Alternatively, please provide an easy way to find out if all writes have failed.

**Comment by soolaugust** [comment]
Hi @jech ,Do you have any reference for this message

` it is only correct to resend the packet if all writes have failed.`

**Comment by Sean-Der** [comment]
@jech What if we include the `ID` or `Label`? Even then the API still feels a little sharp to me. The only thing that can cause the `Track.Write` error is using a failed candidate. In that case we either want the user to `Close()` or restart the candidate. No other success criteria I can think of.

**Comment by jech** [comment]
> Hi @jech ,Do you have any reference for this message

>> it is only correct to resend the packet if all writes have failed.

No reference, but I can explain what I mean.

Suppose you're buffering keyframes in order to reply to PLI or FIR in a timely manner.  If you have a reliable indication that a packet within a keyframe didn't get through, then you could conceivably schedule resending of the packet without waiting for NACK or PLI.  However, in order to do that, you need an indication about which particular senders didn't get the packet.  Hence, the indication that some sender is useless unless you can identify the failed sender.

Hence my suggestion to return an error indication only when *all* senders failed to get the packet.  Sean suggests that the error value identify the failed senders, which is not a bad idea, but might make the API a little too rich.

**Comment by jech** [comment]
> @jech What if we include the `ID` or `Label`? Even then the API still feels a little sharp to me. The only thing that can cause the `Track.Write` error is using a failed candidate.

Hmm... I guess there's too much asynchrony to propagate errors from the `sendto` system call.  Which makes the point somewhat moot.

**Comment by Sean-Der** [comment]
Calling `Write` on a `TrackLocal` will never return a network error. These were all the considerations that went into this decision.

* Returning an error back to the user wouldn't be useful. A PeerConnection doesn't have an ID, so would be hard to identify the offender.
* Returning the non-temporary error breaks DTLS and SCTP. The state then later could be fixed with an ICE Restart. DTLS and SCTP would remain in the broken state.
* It requires users to handle the same state in two Places. They should only be watching `ICEConnectionState` 

@jech @tarrencev please re-open if you disagree! There was a fair amount of churn on this, tried to summarize conversations in different threads and Slack here.
