### ISSUE TITLE
PayloadType and Extension Header ID needs to be set at the Transceiver Level

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#1554]
Currently the `MediaEngine` stores these values at the PeerConnection level. We need to store them at the Transceiver level.

One use case where this is important is the fan-out use case. Without this change the SFU would have to choose either Header ID 1 or 2. You would then have to modify the headers as they flow through. This same restriction applies to PayloadType.
```
FireFox (Header ID 1) ->             ------> Track 1 (Header ID 1)
                           SFU  
Chrome (Header ID 2) ->            -------> Track 2 (Header ID 1)
```

By allowing values per media section we remove the need for users to modify/parse inside the SFU. So you could do the following.
```
FireFox (Header ID 1) ->              ------> Track 1 (Header ID 1)
                            SFU  
Chrome (Header ID 2) ->             -------> Track 2 (Header ID 2)
```

**Comment by Sean-Der** [comment]
The PayloadType and Extension Header ID can be changed on every round of signaling

**Comment by Sean-Der** [comment]
@OrlandoCo maybe I missed something, but for this to work Pion needs to be the offerer. Do we need to add an API to override values at the Transceiver level? They can only be used if `Send` hasn't been called yet.

**Comment by OrlandoCo** [comment]
@Sean-Der There are 2 cases:

1. When Pion is the offerer, pion should negotiate the ext headers with `ext id` set by media engine, atm if pion offers there is no ext header if pion does not negotiate it, thius maybe can be separated in `offerExtHeader` and `anserExtHeader`, because maybe you want to negotiate `twcc` or `audiolevel` in the upstream but not dowstream

2. When Pion is the answerer, every transceivers should be negotiated by it's coressponding media line.

This can be more difficult to impleement, since most users would just like to no enter in many configurations but in some specializes uses case like a SFU a more grain fined control would be better

**Comment by Sean-Der** [comment]
1.) So you want to support `TWCC` in `sendrecv`, `send` or `sendrecv` transceivers only? You aren't interested in configuring it ad-hoc per Transceiver? That is great to hear if so, that is easier to do and requires just MediaEngine API changes.

2.) 👍

**Comment by OrlandoCo** [comment]
>1.) So you want to support `TWCC` in `sendrecv`, `send` or `sendrecv` transceivers only? You aren't interested in configuring it ad-hoc per Transceiver? That is great to hear if so, that is easier to do and requires just MediaEngine API changes.

No, for example in the SFU we support twcc in `RemoteTracks` but not int `LocalTracks`, since we wont react to TWCC RTCP from subscribers. But not sure if this way of work may make harder for other users, since this seems an special case of a SFU, that need more grained control in publishers and subscribers

**Comment by Sean-Der** [comment]
I don't think we can do it for `RemoteTrack` vs `LocalTrack`. We will have issues like what happens when you have a `RemoteTrack` and `LocalTrack` that belong to the same Transceiver, but they have different configurations? We can throw errors, but I would prefer to keep that complexity out.

What we can do though is make it so you can set it at the `MediaEngine` level. You can do `TWCC` only for `recv` only. Then you can have one `send` transceiver and one `recv` transceiver. 

You could actually have this today just by filtering the SDP!
