### ISSUE TITLE
The pfs in recorded video of (ivf or h264 writer) is not correct

### ISSUE THREAD

**Issue by uoosef** [pion/webrtc#1581]
### Your environment.
  - Version: windows 10 pro 10.0.181362.1198 server and golang 1.13
  - Browser: Chrome 84.0.4147.125 on android 8.1

### What did you do?
I build a sfu with ion-sfu repository and I use of recording to disk example to save rtp packets to disk.

### What did you expect?
I recorded a 15 seconds stream but the resulting video plays in 4 seconds!

### What happened?
I have many problems with ivf and h264 writer like random and corrupted frames in the resulting video but the most disturbing issue is that the resulting video's fps is not correct and video frames come after each other very fast.
can anyone guide me to solve this issue?

**Comment by Sean-Der** [comment]
Hey @uoosef I am gonna move conversation to https://github.com/pion/webrtc/issues/696

We are working on improving this in `/v3` but there is only so much we can do under adverse network conditions. Since we don't decode the video we can't request PLIs etc. We are going to have NACK on by default in `/v3`. 

H264 itself doesn't have timing info, so you need to explicitly set it. ivf requires that you gracefully close the file so we can update the header.

I have seen a lot of success with [save-to-webm](https://github.com/pion/example-webrtc-applications/tree/master/save-to-webm) and sending media into [ffmpeg](https://github.com/pion/webrtc/tree/master/examples/rtp-forwarder) and saving there.
