### ISSUE TITLE
AV1 support

### ISSUE THREAD

**Issue by aixinaxc** [pion/webrtc#1670]
When will AV1 support be added to webrtc？

**Comment by Sean-Der** [comment]
Hi @aixinaxc 

It works today! You can call `RegisterCodec` on the `MediaEngine`

we don’t have a packetizer yet however. If you are interested in contributing that would be great. Then we can turn on by default.

thanks

**Comment by tmatth** [comment]
Is there a depacketizer?

**Comment by Sean-Der** [comment]
@tmatth we have neither yet unfortunately!

If this is actually blocking anyone happy to make a priority. This would be a fun first contribution if anyone is interested.

**Comment by tmatth** [comment]
Reference:
https://aomediacodec.github.io/av1-rtp-spec/

**Comment by jech** [comment]
Do any browsers implement it yet?

**Comment by Sean-Der** [comment]
Chrome does [Release Announcement](https://blog.chromium.org/2021/03/chrome-90-beta-av1-encoder-for-webrtc.html)

**Comment by lnogueir** [comment]
> 
> 
> Do any browsers implement it yet?

It has been available in `libwebrtc` for a while, so technically chrome's implemented it.

Check this medium article for details: https://webrtcbydralex.com/index.php/2020/01/27/real-time-av1-in-lib-webrtc-m80/

Some people have been able to set up AV1 encoding on Chrome Canary, as explained here: https://medooze.medium.com/mastering-the-av1-svc-chains-a4b2a6a23925

**Comment by jech** [comment]
Confirmed, I've just managed to push an AV1 flow through Galène.  Essentially, it consisted in adding
```
webrtc.RTPCodecCapability{
		"video/AV1X", 90000, 0,
		"",
		nil,
}
```
at the right point in the code.  The browser is Brave 1.23.71 based on Chromium 90.

**Comment by jech** [comment]
There's no dependency descriptor (or perhaps I'm not negotiating it correctly).

**Comment by Sean-Der** [comment]
One requirement for AV1 support is to add support to our IVFWriter. 

We should add a `*Option...` argument and allow users to specify VP8, VP9 or AV1.

**Comment by jech** [comment]
I think there's also an issue with the samplebuilder.  The samplebuilder
assumes that it is enough to concatenate packet bodies, but I don't think
that's going to work for AV1, since the size of the last OBU in a packet
is omitted.

**Comment by NadeenUdantha** [comment]
maybe useful: https://github.com/NadeenUdantha/DependencyDescriptor

**Comment by dannymn** [comment]
> maybe useful: https://github.com/NadeenUdantha/DependencyDescriptor
> 
> > It looks like this could be implement pretty quickly! Payload Header is all we need to worry about.
> 
> https://gist.github.com/NadeenUdantha/a864b617c19639e8cc506684a2d95745

any news regarding AV1 codec support ?
i'm using for for almost a year inside a chrome as mentioned in the thread
chrome sdp video line includes -> "AV1/90000" (not AV1X any more starting with chrome 91+)
in order to manipulate chrome default encoder or libWebRTC i put in "m=video" line the following order starting with payload 35 (chrome/libwebrtc regsiter AV1 under this payload type id)
////AV1 support
string newCodecOrder = "m=video 9 UDP/TLS/RTP/SAVPF 35 36 96 97 98 99 100 101";
sdpStr.replace(posCodecOrder, codecOrder.length(), newCodecOrder);

can i ask you guys to add this to ion-sfu as soon as possible? AV1 outperfrom vp8 easily with both quality and bandwidth usage...

many thanks!
Danny

**Comment by jech** [comment]
> chrome sdp video line indeed includes -> "AV1/90000" (not AV1X any more starting with chrome 91 and above)

Thanks for the info.  I've just adapted Galene to the new name https://github.com/jech/galene/commit/6fbdf0eab2c9640e673d9f9ec0331da24cbf2c4c

**Comment by jech** [comment]
I think there might be a misunderstanding.  This bug tracker is about Pion, a WebRTC library.  This issue is about changes to Pion WebRTC that might be required for full AV1 support.

Galene and Ion-SFU are two *distinct* projects that use Pion.  Galene has basic support for AV1, even though the support in Pion is incomplete.  I have no idea about Ion-SFU.

If you have patches against Pion to submit, you should submit them here.  If you have patches against Ion-SFU, you should submit them at https://github.com/pion/ion-sfu

**Comment by dannymn** [comment]
Dear Juliusz,
my remarks regarding Pion missing AV1 support has nothing with Galene project.
I'm interested in adding AV1 support in ion-SFU, as far as i understand and maybe i'm wrong here, ion-SFU and Pion sharing same WebRTC stack code (or perhaps better say ion-sfu using Pion webrtc support) , so adding AV1 support in Pion, should find its way quickly into relying Ion-Sfu, am i wrong here? i could try posting it on ion-sfu, but as far as i checked, i didn't see any open issue regarding AV1 support in ion-SFU yet...cheers!
