### ISSUE TITLE
You sholdn't use import from "internal" in examples

### ISSUE THREAD

**Issue by archekb** [pion/webrtc#1696]
Go did't like internal import from external package
```
package command-line-arguments
        cmd/pion/main.go:12:2: use of internal package github.com/pion/webrtc/v3/examples/internal/signal not allowed
```

https://github.com/pion/webrtc/blob/c3ba92bf4ad8d06b21d62f48f04cba246b4ff3d2/examples/save-to-disk/main.go#L14

**Comment by Sean-Der** [comment]
Hey @archekb 

Sorry for the frustration, but this is by design. `github.com/pion/webrtc/v3/examples/internal/signal` isn't a public API, but some utilities that exist to make our examples terser. We may change them in the future and don't want users importing them.

If you want to use `save-to-disk` I would copy `internal/signal` into your own project. Then you can rewrite the imports accordingly. 

thanks for using Pion!
