### ISSUE TITLE
use of internal package github.com/pion/webrtc/v3/examples/internal/signal not allowed

### ISSUE THREAD

**Issue by nilopaim** [pion/webrtc#1701]
### Your environment.
  - Version: Go version go1.16 windows/386
  - Browser: never mind

### What did you do?

I'm trying to compile the example at https://github.com/pion/webrtc/tree/master/examples/broadcast

### What did you expect?
Compilation Ok.

### What happened?
main.go:13:2: use of internal package github.com/pion/webrtc/v3/examples/internal/signal not allowed

**Comment by Sean-Der** [comment]
Hey @nilopaim 

Sorry for the frustration, but this is by design. `github.com/pion/webrtc/v3/examples/internal/signal` isn't a public API, but some utilities that exist to make our examples terser. We may change them in the future and don't want users importing them.

Go requires projects to be in a specific structure. `~/go/src/github.com/pion/webrtc` and if you have a custom layout it thinks you are working on a new project.

If you want to use `brodcast` I would copy `internal/signal` into your own project. Then you can rewrite the imports accordingly. 

thanks for using Pion!
