### ISSUE TITLE
Improve cryptic "excessive retries in CreateOffer" error message

### ISSUE THREAD

**Issue by myfatemi04** [pion/webrtc#1702]
If a user doesn't attach a `MediaEngine` with at least one codec in the parameters of `NewAPI`, subsequent calls to `PeerConnection.CreateOffer` will always result in an error with the message `excessive retries in CreateOffer`. This message is a little cryptic and doesn't point to a direct way to resolve it; instead, it could suggest adding a MediaEngine with at least one codec.

# Example code that causes the error

```go
settingsEngine := webrtc.SettingEngine{}

// ... //

rtc = webrtc.NewAPI(webrtc.WithSettingEngine(settingsEngine))

peerConnection, err := rtc.NewPeerConnection(webrtc.Configuration{})

// ... //

peerConnection.CreateOffer(nil)

```

# Example code that resolves the error

```go
settingsEngine := webrtc.SettingEngine{}

// ... //

mediaEngine := webrtc.MediaEngine{}
mediaEngine.RegisterDefaultCodecs()

rtc = webrtc.NewAPI(webrtc.WithSettingEngine(settingsEngine), webrtc.WithMediaEngine(&mediaEngine))

peerConnection, err := rtc.NewPeerConnection(webrtc.Configuration{})

// ... //

peerConnection.CreateOffer(nil)

```

**Comment by jech** [comment]
See #1565.  The error message indicates that `CreateOffer` failed to converge after a large number of iterations.  It should never happen in correct code, it's just a last-ditch check to prevent your application from hanging.

The actual bug is that we ever got into a state where we don't converge.  The lack of a suitable codec should have been found approximately a million function calls earlier, and a useful error value returned to the caller.  Unfortunately, it's difficult to find all cases of an incorrect configuration, so in some cases you get the internal error message.

**Comment by Sean-Der** [comment]
Thank you so much for the issue @myfatemi04 

I added some additional error handling so this is caught before the general 'excessive retries' catch takes place.
