### ISSUE TITLE
Is RTCIceCandidatePairStats implemented?

### ISSUE THREAD

**Issue by tubzby** [pion/webrtc#1963]
### Your environment.
  - Version: *1231f4f8*
  - Browser: *Not related*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

According to this  [comment](https://github.com/pion/webrtc/issues/610#issuecomment-506420414
),  RTCIceCandidatePairStats is implemented. but when I print out the CurrentRoundTripTime, it's always 0.

Print statistics using GetStat api:
```golang
func  logStatistics() {
	report := pc.GetStats()
	for _, s := range report {
		logger.Infof("report: %+v", s)
	}
}
```

### What did you expect?

The correct CurrentRoundTripTime which indicates the current network status.

### What happened?

Always get 0 of CurrentRoundTripTime

**Comment by Sean-Der** [comment]
@tubzby It looks like some of them have been implemented, but not all https://github.com/pion/ice/blob/master/agent_stats.go#L18


Will close this since we have #610 still. We haven't had any contributors actively working in this area, so I don't anticipate any changes in the near future.

If you are interested in implementing these I am happy to answer any questions here or on [Slack](https://pion.ly/slack). Would love your help!
