### ISSUE TITLE
add example of using trickle ice

### ISSUE THREAD

**Issue by maddanio** [pion/webrtc#2030]
Hello,

The examples mention a lot that one should use trickle ICE in production, but no example of that. I find it hard to navigate webrtc terms, so a simple example would be really really nice. in our case we are not restricted to a single signaling message as we have a working websocket connection between server and client.

**Comment by maddanio** [comment]
Trouble is i have nothing to merge because i don't know how to do it :)

**Comment by Sean-Der** [comment]
[pion-to-pion](https://github.com/pion/webrtc/tree/master/examples/pion-to-pion) does trickle ICE between two Go agents.

[sfu-ws](https://github.com/pion/example-webrtc-applications/tree/master/sfu-ws) does trickel ICE between Go and Web/Mobile.

I hesitate to recommend either because they are demonstrating other things as well. Would be great to have a Trickle only example (like you suggest). People can see only that in action. Also great place to explain why trickle is important as well :)

**Comment by maddanio** [comment]
the latter one looks interesting enough. maybe I will get round to distilling it down to a single connection example

**Comment by maddanio** [comment]
thanks!

**Comment by Sean-Der** [comment]
Hey @maddanio you interested in taking this? If not I have time tomorrow and will code something up :)

thanks!

**Comment by maddanio** [comment]
Go for it :)

**Comment by Sean-Der** [comment]
@maddanio Pushed! Mind trying that out?

Does it do a good job explaining things? Is the example simple enough to learn/follow?

**Comment by maddanio** [comment]
nice job! Regarding the js communication I really liked the approach from sfu-ws. Also having video data streaming at least from the server to the client would be neice maybe? but still, it does the job of demonstrating the basics.
