### ISSUE TITLE
supporting Remove Transceiver

### ISSUE THREAD

**Issue by lenaky** [pion/webrtc#2068]
### Your environment.
  - Version: Latest
  - Browser: Any Browsers
  - Other Information - N/A

### What did you do?

I'm developing SFU Server using ion-sfu. 
Client can send `Join` with offer SDP repeatedly and this happens negotiate or re-negotiate Publisher's peerConnection.
`SetRemoteDescription` keeps adding transceiver for `Receiver` so `peerConnection.rtpTransceivers` keeps growing memory because Transceiver references allocated variables.
As much as this PeerConnection alive, memory never shrinks.

### What did you expect?
When Transceiver is stopped, all references in PeerConnection is removed.

### What happened?

I don't know keeping transceivers is standard behavior or not. If not, how about providing `RemoveTrasnceiver` func?
heres debugging log using `delve`
```
v3.PeerConnection {
	statsID: "PeerConnection-1640932940100021665",
	mu: sync.RWMutex {
		w: (*sync.Mutex)(0xc0002e0d90),
		writerSem: 0,
		readerSem: 0,
		readerCount: 0,
        ...
        ....
	rtpTransceivers: []*webrtc/v3.RTPTransceiver len: 103, cap: 128, [
		*(*"webrtc/v3.RTPTransceiver")(0xc000234c60),
		*(*"webrtc/v3.RTPTransceiver")(0xc000234e10),
                 ...
                 ...
    		*(*"webrtc/v3.RTPTransceiver")(0xc000473680),
		*(*"webrtc/v3.RTPTransceiver")(0xc00193eab0),
```

**Comment by lenaky** [comment]
no references is stored. it isn't main reason that memory grows I think.

**Comment by r1a2y3** [comment]
Hi lenaky, I also meet this question too. Can you give me any advice? Thanks a lot!

In my opinion, more and more rtpTransceivers will cause SDP negotiation to bring a lot of overhead in calling CreateOffer, which needs to generate a lot of objects. In my test of continuously join and leave a large conference, the memory of the server will quickly increase because of this, until the process is killed due to OOM. It is not a leak, but because rtpTransceivers is not removed. 

So I think this issue still needs to be resolved.
