### ISSUE TITLE
Not reading ice server credentials & ontrack issue with WASM

### ISSUE THREAD

**Issue by Chimerax2** [pion/webrtc#2124]
I am opening a peer connection via the WASM example and i'm using my turn server in the config with all the info (url, username, credential) but in the browser i get error:
`JavaScript error: Failed to construct 'RTCPeerConnection': Both username and credential are required when the URL scheme is "turn" or "turns".`

I build the config with the following code:

	config := webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs:       []string{"turn:myturnserver:443?transport=tcp"},
				Username:   "myusername",
				Credential: "mycredential",
			},
		},
	}
	

Also if i try to use OnTrack i get error again:
```
./main.go:65:4: pc.OnTrack undefined (type *webrtc.PeerConnection has no field or method OnTrack)
./main.go:65:22: undefined: webrtc.TrackRemote
```

**Comment by Sean-Der** [comment]
Hi @Chimerax2 

I just added support for WASM and Credentials in `v3.1.30`

Media support for WASM is a bigger topic. Since `pion/webrtc` doesn't bundle decoders or have a DOM to tie media objects with that is harder to implement.

I want to add WASM support to `pion/mediadevices`. I am more pessimistic about `OnTrack` support. I would love to explore it though !
