### ISSUE TITLE
Infinite loop in Mux.NewEndpoint

### ISSUE THREAD

**Issue by jech** [pion/webrtc#2180]
Commit 93b0f2a75eae5139362faf5346f0b6d53cfbf20d introduced an infinite loop in a library function.  The discussion in bug #2152 seems to indicate this papers over a bug somewhere else — SCTP should be able to recover from a lost packet, so there's no reason to introduce the busy wait when the mux happens to be full.

At the very least, we should make sure that there is a hard bound on the amount of time we spend in the busy wait.  Ideally, we should find what is the root cause of the issue noted by @iamcalledrob, and fix that properly.

**Comment by Sean-Der** [comment]
@jech that's a good call out! The other thing is that we are going to degrade the media experience if SCTP has issues. Catching the `packetio.ErrFull` as a non-fatal error is the right thing to do. 

@iamcalledrob What happens if we drop the sleep, and just check the error?

```
  _, err := endpoint.buffer.Write(buf)
  if errors.Is(err, packetio.ErrFull) {
    return nil
  }

  return err
```

It fails the new test you added, but I believe it should be fine with SCTP.

**Comment by iamcalledrob** [comment]
@Sean-Der @jech

I tested dropping the sleep and put up a quick PR with the fix: https://github.com/pion/webrtc/pull/2184. The only trade-off is that theoretically the tests may not always pass, because test.StressDuplex can't handle dropped packets. This was always the case though, even before my previous patch, so it's unlikely to be an issue (I'd think?)
