### ISSUE TITLE
excessive retries in CreateOffer - Single Port

### ISSUE THREAD

**Issue by Chimerax2** [pion/webrtc#2243]
I'm receiving `excessive retries in CreateOffer` error when using the ice single port option.

The only thing that is different than the example is that instead of only datachannel i'm also creating a video and audio stream and the backend is creating the offer instead of the frontend.
Couldn't find anything more specific about why this is occuring

**Comment by Sean-Der** [comment]
Hi @Chimerax2 !

That is happening because you aren't using a MediaEngine. Pion attempts to create the Offer, but has no codecs (and keeps attempting to generate).

You will want to do something like [this](https://github.com/pion/webrtc/blob/157220e800257ee4090f181e7edcca6435adb9f2/examples/simulcast/main.go#L32-L61)

Just exclude [these](https://github.com/pion/webrtc/blob/157220e800257ee4090f181e7edcca6435adb9f2/examples/simulcast/main.go#L36-L44) lines if you aren't interested in Simulcast.

Please re-open if that doesn't help!
