### ISSUE TITLE
The simulcast example only shows 2/3 tracks

### ISSUE THREAD

**Issue by SimonBrandner** [pion/webrtc#2297]
### Your environment.
  - Version: `master`
  - Browser: Chrome 104.0.5112.101

### What did you do?

Followed the instructions in the example

### What did you expect?

See 3 tracks 

### What happened?

I can only see 2/3 (the last encoding specified in `sendEncodings` is missing - `q`). `OnTrack` only gets called twice instead of thrice

**Comment by SimonBrandner** [comment]
On FF 102.1.0esr `OnTrack` is fired thrice but I can't see any video from Pion

**Comment by SimonBrandner** [comment]
Turns out that if I do `getUsermedia()` requesting a FHD stream, everything works fine on Chrome though I am still not getting any video on FF

**Comment by kcaffrey** [comment]
I am unsure about Firefox, but in Chrome it's expected behavior that you won't always get all the simulcast encodings you ask for. Chrome limits the simulcast layers sent based on resolution and bitrate.

You can see the code Chrome uses to limit the number of layers [here](https://chromium.googlesource.com/external/webrtc/+/master/media/engine/simulcast.cc#79). If the highest layer's resolution is below 960x540, you'll only get 2 layers (and only 1 if below 480x270).

**Comment by SimonBrandner** [comment]
Hmm, so it looks like all three tracks actually have almost the same resolution with the full res track being super laggy - what am I missing this time?

**Comment by SimonBrandner** [comment]
Turns out FF requires us to do `setParameters()` which doesn't match the spec but it works
