### ISSUE TITLE
Backport SampleBuilder bugfixes from webrtc-rs (if needed)

### ISSUE THREAD

**Issue by tmatth** [pion/webrtc#2323]
Quoting @k0nserv (see https://github.com/webrtc-rs/webrtc/pull/309/)

> Improve Sample Builder handling of padding packets
> 
> When sending video streams that are fairly static, such as a screen
> share of an inactive screen, libWebRTC will insert padding RTP packets.
> These were not correctly handled by sample builder, because of this
> SampleBuilder would throw away packets carrying actual media.
> 
> There was also a bug where dropping packets because the sample head was
> not at a partition start would double count the dropped packets(once in
> build_sample and once in purge_buffers.

Apparently Pion's samplebuilder may have the same issues.

The steps I guess would be to:
- [ ] confirm with e.g. a testcase that these bugs are present in pion
- [ ] backport the changes as needed

### Your environment.
  - Version: 5c13a6ecd6ff37c7958a059d1850baa96356af17
  - Browser: N/A

**Comment by k0nserv** [comment]
https://github.com/webrtc-rs/webrtc/pull/303 might also be of interest.

The way to reproduce the issues I've observed is to send a screen share video track of relatively static content(I a tab with chrome://webrtc-internals) and then run this through `SampleBuilder`. Then attempt to play back this samples, either by saving them to disk or by sending them out again as RTP.

The test cases in https://github.com/webrtc-rs/webrtc/pull/309 could be ported directly and should showcase the issue if it exists.

**Comment by jech** [comment]
Interesting.  Could you please explain why you only drop empty packets when the timestamp is constant, rather than dropping all empty packets?

**Comment by k0nserv** [comment]
There's no specific code that drops empty packets, what happens is: SampleBuilder tries to build samples by looking for continuous(in terms of sequence number) stretches of RTP packets where the first packet is identified as the start of a partition(this is codec specific) and the last packet is identified as the end of a partition(either via the RTP marker bit being set or by detecting a differing timestamp). 

What we've done in the webrtc-rs is add code that can identify these empty padding packets to make it possible to distinguish between dropped padding packets(which are inconsequential) and dropped packets that carry media. Further, we discovered that in some instances the code to drop packets would get confused by these padding packets and, incorrectly, drop media packets. This happens with sequences like

```
p1(t=1, start=true)
p2(t=1)
p3(t=1)
p4(t=1, marker=true)
p5(t=1, padding=true)
p6(t=1, padding=true)
p7(t=1, padding=true)
p8(t=2, start=true, marker=true)
p9(t=2, padding=true)
p10(t=2, padding=true)
p11(t=2, padding=true)
```

Here SampleBuilder will build a sample of `p1` through `p4` and then, when `p8` is added it will identify `p4` through `p8` as a partition(because the marker bit is set for `p8`). Then, because `p4` is not the start of a partition, it will drop all these packets, including `p8` which contains media. The problem is that `p8` is considered to belong to the same partition as `p4`, but it shouldn't be because its timestamp differs.

**Comment by jech** [comment]
Ah, I see.  I think the issue does not occur in https://github.com/jech/samplebuilder, which will correctly identify p5 as the start of a new partition: https://github.com/jech/samplebuilder/blob/master/samplebuilder.go#L274

Thanks for the tests, I'll port them to make sure.

**Comment by jech** [comment]
Confirmed: https://github.com/jech/samplebuilder/commit/9cfa4cad2157b6c67cf8c9f2a725ead20a3b5dac

**Comment by tmatth** [comment]
I've created a draft PR here, unless I messed something up it seems like the durations coming out of samplebuilder don't match:
https://github.com/pion/webrtc/pull/2328

**Comment by jech** [comment]
Yes, they're off by one: webrtc-rs returns the duration interval between the previous and the current sample, while mine returns the interval between the sample and the next one.

At any rate, they're not useful, and they're only provided for backwards compatibility: instead of the sample duration, you should be using the sample's timestamp.
