### ISSUE TITLE
data-channels example requires internal package and so can't be built locally

### ISSUE THREAD

**Issue by peredwardsson** [pion/webrtc#2338]
### Your environment.
  - Version: go version go1.19.2 darwin/amd64
  - Browser: Safari Version 16.0 (17614.1.25.9.10, 17614)
  - Other Information - I'm trying to learn about Go in the context of WebRTC, two topics which are new to me. This means I am sort of confused in general. I apologise ahead of time if my expectations are odd compared to reality, and appreciate any pointers in the right direction in that case. 

### What did you do?
Download the `main.go` file from the (examples/data-channels)[https://github.com/pion/webrtc/tree/master/examples/data-channels] folder. In bash, type `go mod tidy && go run main.go`.

### What did you expect?
I expect it to wait for me pasting my offer into stdin.

### What happened?
```
> go run main.go                                                                                                                                                                         (base) 
package command-line-arguments
        main.go:9:2: use of internal package github.com/pion/webrtc/v3/examples/internal/signal not allowed
```

Since I can't run these packages locally, I have some trouble understanding what it is supposed to do.

**Comment by Sean-Der** [comment]
Hi @peredwardsson 

Sorry this took so long to respond! I was on a break from `pion/webrtc`. The reason this code is in the `internal` package is that users can't depend on it. Users are expected to copy this code if they want to put it in their own project.

To run the `data-channels` example I usually do this.

```
$ git clone https://github.com/pion/webrtc
$ cd webrtc/examples/data-channels
$ echo eyJ0eXBlIj.... | go run main.go
```

and this will print out the Answer. Copy that and you will messages for it working.

```
eyJ0eXBlIjoiY....

Peer Connection State has changed: connected
New DataChannel foo 1374393305410
Data channel 'foo'-'1374393305410' open. Random messages will now be sent to any connected DataChannels every 5 seconds
Sending 'vnhSnCnXmIgyHsz'
Sending 'ALjNhjcuGssQpQb'
Sending 'htaJvHUpoPsDgkA'
Sending 'CWFLDCdyQkafBTh'
Sending 'yzYgtUpPdrTGbsq'
```

Go will download all the libraries for you etc...

----

When it comes time to start your own project you can copy the internal folder. I would suggest reviewing it and understanding what it is doing though. In most cases base64'ing the SDP isn't necessary, we just do it since we are doing copy+paste.

I am closing for now, but please re-open if you are still having problems. I am also available on the [Pion Slack](https://pion.ly/slack)
