### ISSUE TITLE
DisableMediaEngineCopy(true) not working correctly with sending video from chrome to firefox

### ISSUE THREAD

**Issue by justCodeLife** [pion/webrtc#2381]
### Your environment.
  - Version: v3.1.50
  - Browser: Chromium 108.0.5359.124 , Firefox 108.0.2

### What did you do?
Send webcam video from chrome to pion and then forward that to other peer with firefox browser

### What did you expect?
Receive video and show in firefox

### What happened?
With setting DisableMediaEngineCopy(true) on setting engine
video sent from chrome to firefox forwarded by pion will not display.

firefox -> pion -> firefox is ok ,
chrome -> pion -> chrome is ok ,
firefox -> pion -> chrome is ok ,

only chrome -> pion -> firefox is not ok

**Comment by Sean-Der** [comment]
Hi @justCodeLife 

When you set `DisableMediaEngineCopy(true)` you will not be able to use the MediaEngine across multiple browsers. PayloadTypes are different for each browser, so the first browser to connect will be the only one supported.

If possible I would suggest to stop using `DisableMediaEngineCopy`. This existed for users upgrading from `/v2`, but will cause issues. What features/behaviors are you getting from `DisableMediaEngineCopy`?

I am going to close the issues since the issue of 'Multiple browsers not working' is known. I will also add a comment so this is more clear to users! I am happy to help migrate your code/answer any questions here so you can stop using it.
