### ISSUE TITLE
Add fuzz testing to parser code

### ISSUE THREAD

**Issue by maxhawkins** [pion/webrtc#251]
Randomized testing with [go-fuzz](https://github.com/dvyukov/go-fuzz) will help identify parser edge cases we haven't thought of yet and potential "packets of death" that could crash our code.

- [ ] pkg/rtcp
- [ ] pkg/rtp
- [ ] internal/dtls
- [ ] internal/sdp
- [ ] others (?)

**Comment by Sean-Der** [comment]
Closing this since we have issues in all the individual repos.

* https://github.com/dtls has fuzz testing
* https://github.com/rtcp has fuzz testing
* https://github.com/stun has fuzz testing
* https://github.com/turn has fuzz testing
* https://github.com/sdp has fuzz testing
* https://github.com/sctp has covering ticket
* https://github.com/rtp has covering ticket

It would be great if we could get projcets into `go-fuzz` and get some sort of 'code coverage'. We need to find someone that is interested in finishing this up. Maybe this would be a good thing to ask on Twitter for help?

@maxhawkins @josharian any ideas? You both seem passionate about this :)

**Comment by AdamKorcz** [comment]
> It would be great if we could get projcets into go-fuzz
@Sean-Der Could you elaborate on what you mean by this? I might be able to contribute on fuzzing webrtc

**Comment by Sean-Der** [comment]
@AdamKorcz yea! Sorry I think I meant [oss-fuzz](https://github.com/google/oss-fuzz). Right now we don't run our fuzzers, so they aren't doing much currently :(

We can either get them running over there OR setting up something ourselves.

**Comment by AdamKorcz** [comment]
Awesome. I will be happy to look into that.
I may be looking in the wrong places, but I don't see the fuzzers in this repo. Could you post a link to them?

**Comment by Sean-Der** [comment]
`pion/webrtc` doesn't have any itself. It gets stuff already processed in from it modules.

[dtls](https://github.com/pion/dtls/tree/master/fuzz/corpus)
[stun](https://github.com/pion/stun/tree/master/fuzz)
[sdp](https://github.com/pion/sdp/blob/master/fuzz.go)
[rtcp](https://github.com/pion/rtcp/blob/master/fuzz.go) 

It looks like STUN/DTLS are the only ones that are really valuable right now. So I see three steps of work.
* Get fuzz testing working locally
* Get some corpuses
* Set up infra so they are always running

You know WAY more about this stuff then me. So please do w/e you think is right. Tell me what I can do to help!

**Comment by AdamKorcz** [comment]
That is awesome. I see some ways to proceed from here.

In order to setup continuous fuzzing through oss-fuzz, it helps with referencing adopters/users, as oss-fuzz would like to contribute to the security of projects that impact lots of people as well as companies using open source software in production. Do you know of adopters/users and is it something you can post publicly when setting up an integration-application?

Also, email addresses of maintainers who are to receive potential bug reports will have to be added to a public list. If this is not okay, please let me know.

**Comment by Sean-Der** [comment]
I would start with `Sean DuBois <sean@pion.ly>`

Can share a list of companies privately. Developers reach out to me privately with questions. I don't want to get them in trouble with their employers though.

**Comment by AdamKorcz** [comment]
Duly noted. All details in the application process for oss-fuzz are public. It is understandable that users would like to not advertise their software, and in that case it would be sufficient to name the impact based on the size/revenue of the companies using webrtc.  If that would work, and some larger companies are using webrtc, then should be good.

**Comment by Sean-Der** [comment]
That works for me! Can I email you directly with the list of companies that I know of?

**Comment by AdamKorcz** [comment]
Sure, feel free to send over the list at Adam/-at-/adalogics/-dot-/com
