### ISSUE TITLE
The ivf file generated by the example 'save to disk' appears to be corrupt.

### ISSUE THREAD

**Issue by VacantHusky** [pion/webrtc#2520]
- Version: v3@v3.2.13
  - Browser: Edge 115.0.1901.183 (正式版本) (64 位)

I tried running examples\save-to-disk.
He generated ivf and ogg files. I used VLC to open the ivf file. It played for 7 seconds and then automatically exited. The Progress bar shows that the length of the video is 30 seconds.
May this file be damaged?

**Comment by Sean-Der** [comment]
Hi @VacantHusky 

The issue is that the IVF file wasn't properly closed. Pion creates a ivf file with a default of 30 seconds. When the IVF file is closed we update the frameCount [here](https://github.com/pion/webrtc/blob/master/pkg/media/ivfwriter/ivfwriter.go#L194)

In `save-to-disk` that happens [here](https://github.com/pion/webrtc/blob/master/examples/save-to-disk/main.go#L145) when `ICEConnectionState` goes to failed.  

Can you try running the example again. This time close your browser and wait for Pion to exit gracefully. 

Maybe having a default value of 30 seconds is wrong. Maybe we should have a default value of 0, could you try that and see if VLC handles it more gracefully?

thank you!

**Comment by VacantHusky** [comment]
Thank you. I am sure I have closed the browser and waited for Pion to exit gracefully, but VLC still cannot play properly. However, it's okay. Being able to play normally on the browser already meets my needs.
