### ISSUE TITLE
Issue with save-to-disk example in pion/webrtc project

### ISSUE THREAD

**Issue by VacantHusky** [pion/webrtc#2526]
Dear pion/webrtc team,

I hope this message finds you well. I wanted to start by expressing my appreciation for the fantastic work you've done with the pion/webrtc project. It's an excellent tool, and I'm grateful for the opportunities it has provided.

However, I've come across a particular issue while using the "save-to-disk" example from the project's repository. After establishing a peer-to-peer connection, the remote user switches from camera 1 to camera 2. The remote user, who is on the browser end, uses the RTCPeerConnection.sender.replaceTrack method for this switch. Unfortunately, on the receiving end, the saved recording still shows the video from camera 1, even though the remote user has switched to camera 2.

I have been trying to troubleshoot this problem, but I haven't been able to find a solution. I've checked the documentation and browsed through the code, but I can't pinpoint the issue.

Could you kindly assist me in resolving this matter? Any guidance, suggestions, or code modifications that would enable the save-to-disk example to capture the correct video feed after the camera switch would be greatly appreciated.

Thank you for your time and consideration. I'm looking forward to your response.

Best regards

**Comment by Sean-Der** [comment]
Hi @VacantHusky 

My assumption is that this isn't a pion/webrtc issue. `save-to-disk` is just accepting the incoming rtp packets, it sounds like the `replaceTrack` on the remote end isn't working.

`replaceTrack` may fail if the `RTCRtpSender` isn't able to support the new MediaStreamTrack. Was the returned promise resolved or rejected?

I am hoping you got things working! This issue was filed over a year ago, so I am going to resolve. If you are still have problems please re-open I am happy to help here or on [Slack](https://pion.ly/slack)
