### ISSUE TITLE
Not handling SCTP ParamType 32769 

### ISSUE THREAD

**Issue by daweifeng** [pion/webrtc#2618]
### Your environment.
  - Version: pion/webrtc@v3.2.23, go@1.21
  - Client: [libdatachannel](https://github.com/paullouisageneau/libdatachannel)
  - Other Information - related issue: https://github.com/paullouisageneau/libdatachannel/issues/1030

### What did you do?

I am trying to establish a WebRTC connection between a C++ client using [libdatachannel](https://github.com/paullouisageneau/libdatachannel) and `pion/webrtc`.  While using the latest commit from `libdatachannel`, the WebRTC connection keeps failing because `libdatachannel` implemented `SCTP_ACCEPT_ZERO_CHECKSUM`, which will send a SCTP ParamType 32769. It is not correctly handled by `pion/webrtc` causing the connection to failed. More discussion can be found on this Github discussion: https://github.com/paullouisageneau/libdatachannel/issues/1030 

Here is a log from `pion/webrtc`
```
sctp WARNING: 2023/11/15 22:28:55 [0xc0001c41e0] unable to parse SCTP packet failed to unmarshal INIT body: failed unmarshalling param in Init Chunk: unhandled ParamType: Unknown ParamType: 32769
sctp WARNING: 2023/11/15 22:28:55 [0xc0001c41e0] unable to parse SCTP packet failed to unmarshal INIT body: failed unmarshalling param in Init Chunk: unhandled ParamType: Unknown ParamType: 32769
ice TRACE: 22:28:55.776219 selection.go:176: Checking keepalive
sctp WARNING: 2023/11/15 22:28:56 [0xc0001c41e0] unable to parse SCTP packet failed to unmarshal INIT body: failed unmarshalling param in Init Chunk: unhandled ParamType: Unknown ParamType: 32769
ice TRACE: 22:28:57.777205 selection.go:176: Checking keepalive
```

### What did you expect?
I am not an expert of WebRTC, but based on my discussion on with the auther of `libdatachannel`,  ParamType: 32769 should be handled based on [RFC9260](https://www.rfc-editor.org/rfc/rfc9260.html#section-3.2.1)

**Comment by Sean-Der** [comment]
Thanks for the ticket @daweifeng!

We need to get https://github.com/pion/sctp/pull/284 merged. I will review

If you are interested @daweifeng I would appreciate your help reviewing the PR :)

**Comment by daweifeng** [comment]
Thank you! The PR fixes my issue. I will take a look at the PR as well!

**Comment by paullouisageneau** [comment]
@Sean-Der This has been marked as completed but the corresponding PR is not merged. The bug is still present and is breaking compatibility between pion and libdatachannel 0.20.

As discussed in https://github.com/paullouisageneau/libdatachannel/issues/1030#issuecomment-1800012035, the actual issue is not that parameter type 0x8001 is not handled (which is implemented by https://github.com/pion/sctp/pull/284), it's that unmarshalling in pion seemingly fails on all unhandled parameters. 

An SCTP endpoint does not need to support `SCTP_ZERO_CHECKSUM_ACCEPTABLE` extension to connect with an endpoint that does. According to [RFC 9260](https://www.rfc-editor.org/rfc/rfc9260.html#section-3.2.1) that the endpoint behavior must depend on the highest-order two bits of the parameter type. Here it's 10, so the endpoint must skip the parameter and continue to process other parameters if it doesn't know it. Failing on unknown parameters breaks if peers attempt to negotiate SCTP extensions.
