### ISSUE TITLE
Decoding Opus packets

### ISSUE THREAD

**Issue by inevolin** [pion/webrtc#2647]
I am looking for a Go implementation/library for decoding Opus packets. The Readme states this library supports Opus and PCM formats, but I cannot find an API/example which decodes Opus to PCM.

I already tried this repo but it's not supporting all config types https://github.com/pion/opus/

For the time being I'm using Go bindings for Opus (C binaries) but this is not ideal/cross-compatible (for M1) https://github.com/layeh/gopus

**Comment by Sean-Der** [comment]
Hi @inevolin 

pion/webrtc doesn't provide media coding. Many users just use Pion to pass through/proxy media, so don't want to push that dependency on them.

[pion/opus](https://github.com/pion/opus) only has a SILK decoder unfortunately. I don't anticipate having time anytime soon for CELT! 

I use [hraban/opus](https://github.com/hraban/opus) in my projects today. You could also use libav or GStreamer. 

I am going to close the issue since nothing actionable in this repo for this issue. If you want to convert it to a discussion or discuss on [Slack](https://pion.ly/slack) happy to help however I can!

thanks for using Pion, and sorry that implementing this is harder then it should be :/
