### ISSUE TITLE
Is there any example where the original h264 data can be sent to pion directly at the interface layer?

### ISSUE THREAD

**Issue by gongluck** [pion/webrtc#2717]
I have raw stream from other framework and they will work in the same server with pion.

I can send my raw h264 to pion?

I am sorry but i havent found that example in the source code.

**Comment by Sean-Der** [comment]
Hi @gongluck 

Check out https://github.com/pion/example-webrtc-applications/tree/master/play-from-disk-h264

You will create a TrackLocalStaticSample and then write h264 to it.

I am going to close since there in no actionable dev task. But happy to help more here or on [Slack](https://pion.ly/slack)

**Comment by gongluck** [comment]
> Hi @gongluck
> 
> Check out https://github.com/pion/example-webrtc-applications/tree/master/play-from-disk-h264
> 
> You will create a TrackLocalStaticSample and then write h264 to it.
> 
> I am going to close since there in no actionable dev task. But happy to help more here or on [Slack](https://pion.ly/slack)

thanks a lot
