### ISSUE TITLE
The connection status has failed,Why is the read function still blocking?

### ISSUE THREAD

**Issue by xdeng** [pion/webrtc#2891]
### Your environment.
  - Version: v4.0.0-beta.29
  - Browser: 
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

data-channels-detach

### What happened?
The connection status is

OnConnectionStateChange: disconnected
OnConnectionStateChange: failed

dataChannel.Detach() ---> ReadWriteCloser, Why doesn't it fail when reading, but keeps blocking?

Need to call peerConnection.Close(), The read function will fail to exit.

**Comment by Sean-Der** [comment]
@xdeng The Detached DataChannel API isn't popular with many users like [this](https://github.com/pion/webrtc/issues/903) issue.

The behavior described here is by design. A PeerConnection that has `failed` can go back to Connecting/Connected! If the user does a `ICE Restart`.

When the PeerConnection goes to `Closed` (DTLS Close or `PeerConnection.Close()` only does that mean that connection is terminally closed.

Sorry about the API frustrations. I am not sure of a better way to do this yet :/
