### ISSUE TITLE
Pion spuriously negotiates transport-cc

### ISSUE THREAD

**Issue by jech** [pion/webrtc#2943]
In Galene, I'm explicitly constructing a MediaEngine with just the right parameters.  However, Pion is still negotiating transport-cc, even though I didn't enable it in the MediaEngine.  More precisely:

  * in v3, transport-cc is negotiated in answers but not in offers [edit: this is not split into 2944];
  * in v4, transport-cc is negotiated in both offers and answers.

Full test at https://go.dev/play/p/IBH55knGgkb

**Comment by kcaffrey** [comment]
I think this might be the culprit: https://github.com/pion/webrtc/blob/e53cbc423a41babfc4da69af404e61228cce4e48/api.go#L57

If you don't provide an interceptor registry, the default interceptors are used (and transport-cc is included in the default interceptors). It appears like this may have been intentional: https://github.com/pion/webrtc/commit/21c5a711d84d35898be2fd1181970588d5f6ef0c

One fix would be to supply an empty interceptor registry if you don't want any interceptors. It is documented on `NewAPI()`, so I suspect it probably was an intentional behavior change in v4, but @Sean-Der can comment on that.

**Comment by jech** [comment]
That would explain the behaviour with v4.  But what about the behaviour with v3, where transport-cc is negotiated in the answer but not in the offer?

> If you don't provide an interceptor registry, the default interceptors are used (and transport-cc is included in the default interceptors).

[...]

> What should I say/would be better do you think @jech ?

My understanding was that simple applications (that want a default set of interceptors) should be using `webrtc.NewPeerConnection`, but that applications that use `api.NewPeerConnection` get exactly what they ask for.  That's a reasonable behaviour that's easy to understand.

I dislike the current beheaviour, but I can live with it.  If you guys decide to keep it, I'll submit a documentation patch.

**Comment by jech** [comment]
I've split the second part of this into #2944, since it appears there is another related bug.

**Comment by jech** [comment]
Thinking about it some more, I don't dislike the new behaviour.  Having `webrtc.NewPeerConnection` have different semantics from `api.NewPeerConnection` is uselessly confusing, and applications that want the old behaviour can easily add an empty `InterceptorRegistry`.
