### ISSUE TITLE
WASM: Add support for certificates and credentials

### ISSUE THREAD

**Issue by albrow** [pion/webrtc#499]
I punted on supporting certificates and credentials in #479, but eventually this is something we should support. It will be a challenge to convert between the Go and JavaScript crypto primitives because they aren't just simple data structures.

**Comment by Sean-Der** [comment]
I enabled credentials in `014b717636ea381086fbf144261a83d922b2db62`

Certificates aren't serializable in JS so I don't see a way we can ever support them in both platforms. So I am happy with what we have today!

**Comment by danielvladco** [comment]
Hi @Sean-Der , I dug up this issue because I am trying to create a browser-to-server connection using libp2p and webrtc direct. Right now the libp2p WebRTC build is broken for wasm since the protocol uses a noice handshake that requires a certificate (check this out https://blog.libp2p.io/libp2p-webrtc-browser-to-server/) 

I was wondering is there a way to generate this certificate on the browser side as well? or has something changed since your last comment and now there is a way to do this?

Thanks!
