### ISSUE TITLE
community: related projects

### ISSUE THREAD

**Issue by backkem** [pion/webrtc#52]
This ticket tracks projects related to pions. These can be projects using pions or projects we want to/are contributing WebRTC support to.

**Media API**

- [vvspacetime/webrtc](https://github.com/vvspacetime/webrtc)
- [maxhawkins/asciirtc](https://github.com/maxhawkins/asciirtc) ([incubated](https://github.com/pions/asciirtc))

**DataChannel**

- [go-libp2p](https://github.com/libp2p/go-libp2p) ([issue](https://github.com/libp2p/go-libp2p/issues/188)) [[WIP](https://github.com/backkem/go-libp2p-webrtc-direct)]
- [WebTorrent](https://github.com/webtorrent/webtorrent) support for [anacrolix/torrent](https://github.com/anacrolix/torrent) ([issue](https://github.com/anacrolix/torrent/issues/138))
- [CoreOS](https://coreos.com) Sean-Der reached out but didn't hear. Someone should email the dev list to see if there is still interest maybe? [project](https://github.com/coreos/go-webrtc-datachannel)
- [LivePeer](https://github.com/livepeer) ([issue](https://github.com/livepeer/lpms/issues/38), [issue](https://github.com/livepeer/project-management/issues/5))
- [decentraland/communications-server-go](https://github.com/decentraland/communications-server-go)
- [nobonobo/ssh-p2p](https://github.com/nobonobo/ssh-p2p)
- [cretz/webrtc-ipfs-signaling](https://github.com/cretz/webrtc-ipfs-signaling)

**Unknown**
- [0xProject/webrtc](https://github.com/0xProject/webrtc)

**Other language implementations**
- JS/Node: [nodertc/nodertc](https://github.com/nodertc/nodertc)
- Python: [aiortc/aiortc](https://github.com/aiortc/aiortc)
- Erlang (no link yet)

**Organize TODO**
* https://github.com/Antonito/gfile
* https://github.com/pion/asciirtc
* https://github.com/maxmcd/webtty
* https://github.com/rtctunnel/rtctunnel
* https://github.com/nobonobo/ssh-p2p
* https://github.com/mxseba/rtc-ssh
* https://github.com/poi5305/go-yuv2webRTC
* https://github.com/rian-hotate/tetoris
* https://github.com/schollz/webrtc-transfer
* https://github.com/machinesworking/myhome
* https://github.com/wwl33695/myrtc
* https://github.com/takutakahashi/wg-connect
* https://github.com/open-domophone/soft-omega2
* https://github.com/mtojek/filegate
* https://github.com/porjo/babelcast
* https://github.com/porjo/mumblet
* https://github.com/cretz/myscreen.live
* https://github.com/deepch/RTSPtoWebRTC
* https://github.com/hoernschen/goat
* https://github.com/discordianfish/infisk8-server
* https://github.com/edwintcloud/classmate
* https://github.com/nacgarg/stereo
* https://github.com/mtharp/gunk
* https://github.com/bashawhm/TheHarmonicInternetNoiseGiver
* https://github.com/s8sg/satellite

This issue can be used for tracking. Please use the [Golang Slack](https://invite.slack.golangbridge.org/) #pion channel or [mailing list](https://groups.google.com/forum/#!forum/pion) for discussions.

**Comment by Sean-Der** [comment]
https://github.com/vvspacetime/webrtc is/was working on an SFU. It would be great if we could support this or do it ourselves eventually.  @vvspacetime still interested in working on this? Anything we can do to support/help, more then happy to share in our README and any dev help you need.

If people can use pion-webrtc to have conferences, and then maybe show them how to do server side video processing would open up cool projects.

**Comment by ericxtang** [comment]
An open source SFU would be very useful.

Another application would be video broadcasting over the data channel. It can help scale the delivery of a very popular stream to many viewers.

With the combination, an internet talkshow applications can be built fairly easily.

**Comment by Sean-Der** [comment]
Hi 

@ericxtang I would love to build something that would be unique/useful for people! I am going to start a email thread on our mailing list to gauge community interest, it would distract from normal pion-WebRTC development. If it is something innovative I would love to build it.

Also we have DataChannels now! Personally I would love to do anything I can to help livepeer, the whole concept is amazing was completely unaware of this space when pion-WebRTC started. So if there is anything I can do feel free to file issues, also happy to work 1:1 if you want to drop me an email sean @ siobud (dot) com

We are also trying to work with the libp2p team, just cleaning up some of our messes before we reach out to them again.

**Comment by reklatsmasters** [comment]
I`m working on pure js webrtc datachannel server for nodejs https://github.com/nodertc. STUN, DTLS and SCTP parts are complete. I hope established connection between pions/webrtc and nodertc will be possible sometime in the future.

**Comment by backkem** [comment]
Thanks for reaching out @reklatsmasters. Your awesome project has been on our radar. We would love to collaborate on a connection example when it becomes possible. We also plan to build a suite of integration tests between pions and other webrtc implementations at some point. A nodertc test would fit in perfectly. Also, feel free to join Slack if you ever want to chat.

**Comment by notedit** [comment]
I am writing another go webrtc server,  https://github.com/notedit/media-server-go,  It is a go binding of  https://github.com/medooze/media-server. Will try to make this work with pions.

**Comment by Sean-Der** [comment]
@noahshrader 

This is something I would love to see on `pion.ly` and people can make PRs to update it as they want!

Something like https://github.com/sindresorhus/awesome so we can have README + website

**Comment by jinleileiking** [comment]
This should be on wiki

**Comment by backkem** [comment]
The only reason I would keep it here is that you can't tag people on the wiki @jinleileiking.

**Comment by goodness-from-me** [comment]
I wonder that you haven't heard about @gortc . They are basically doing the same thing as you do.

**Comment by ernado** [comment]
I think it is because gortc is considered as competing project.

I'm author of gortc and I'm pretty impressed of the pion progress. I'm still working on gortc time to time, doing it from zero helps to understand better WebRTC stack. Also I think that our projects have slightly different focuses.

Anyway I'm routinely directing users to pion project if they need something that still not implemented in gortc :)

**Comment by Sean-Der** [comment]
Hey @ernado great to see you :)

Personally I wish we weren't duplicating work! Everyone says having more implementations is better for everyone. However I think it would better if the community could just finish one DTLS implementation and make it great, instead of a handful of half baked versions.

The only big difference for me is how I have seen is how Pion/gortc approach problems. gortc I think is a lot more detail/performance focused (I wish I was better at this stuff). Pion is more 'product focused' I tend to spend time working with people 1:1 and unblocking people so they can build things. This does accumulate tech debt/things don't get built right the first time.

The only thing that motivates me anymore is seeing the kind of impact Pion can have, and hopefully continues making. Completely new products are being launched because using WebRTC is so much easier now. For me Pion doesn't end with WebRTC either, I have lots more I want to build.

**Comment by ernado** [comment]
Hey @Sean-Der, same to me :)

I thought about it, but duplicating work sometimes helps: we can cross-validate our implementations.
Sometimes we are doing almost 1:1, something we are like fasthttp vs net/http.

About DTLS – actually I'm not sure about both approaches, I've tried to modify go TLS implementation to work with DTLS, because they share a lot of code, but there are too much abstractions and cost of failure is high – it is really scary to miss something and make the whole cryptography fail to provide security. Personally I like pion DTLS library more, it has better architecture.

Yes, you are right, sometimes we approach problems differently.
Also, my project is kinda educational, I'm learning about go optimizations and the whole stun/turn/ice stuff, it really helps to see this picture as a whole.

I'm really thankful for your effort – actually your project is one of my top reasons why I'm still working on mine. Also thank you for popularising WebRTC in to community.

**Comment by Sean-Der** [comment]
@ernado 

Well if you are ever interested I still would love to merge gortc/Pion. You do amazing work, and I think together we could all make something much better then alone. But validating against each other sounds like a fantastic plan also :)

You should join us in [Slack](https://pion.ly/slack) you would love the enthusiasm everyone has for WebRTC. All the interesting conversations/projects being built is really motivating. Also would love to poke your brain on stuff I don't know!

**Comment by xsbchen** [comment]
I created a repo https://github.com/xsbchen/awesome-pion

**Comment by Sean-Der** [comment]
@xsbchen wow, that is amazing! I love that. Would you be up for transferring it to the Pion organization? 

I think https://github.com/pion/awesome-pion would be perfect! Then we can put the 'Awesome Pion' badge in each repo to tell people to check it out :)

this is fantastic, thank you so much for starting it.

**Comment by xsbchen** [comment]
@Sean-Der done

**Comment by Sean-Der** [comment]
@xsbchen fantastic! I pinned it, and will add it to the `pion/webrtc` repo! I will start adding more stuff tonight :) 

Thank you so much for starting this, I think people are really going to find this useful

**Comment by xsbchen** [comment]
So happy that I can do something help. I hope it is useful for the guy who wants to use Pion

**Comment by Sean-Der** [comment]
Closing since we have [awesome-pion](https://github.com/pion/awesome-pion) now! I have made sure everything on here has been moved to that repo.

**Comment by anilthummar** [comment]
Hello Everyone ,
can we set up personal server with pion webrtc ?
i am getting error like below
{
I/flutter ( 8210): [Ion::Client] DEBUG: leave reject: error =>transport error
I/flutter ( 8210): [protoo-client] DEBUG: close()
I/flutter ( 8210): [protoo-client] DEBUG: constructor()
I/flutter ( 8210): [protoo-client] DEBUG: constructor() [url:https://meet.cynod.live/html5client/join?peer=bb48fd89-045a-47b8-b3bc-9761e21cde9c]
}
