### ISSUE TITLE
Connections are not closed

### ISSUE THREAD

**Issue by masterada** [pion/webrtc#629]
Once I call SetRemoteDescription, the pion webrtc starts listening on a number of udp sockets.
- should these sockets be closed automatically (eg: after no connection for x seconds)?
- is there any way to close these listening connections?
  - i could not find one (tried calling PeerConnection.Close, but it did not close them)
- if not, do you have any plans to implement this in the near future?

If this is missing feature, I'm happy to help, if you could provide a bit of guidance.

**Comment by Sean-Der** [comment]
Hey @masterada 

* They are only closed when you call `PeerConnection.Close`
  - With WebRTC you can change candidates at anytime (it handles one network interface going away and switching to another one etc..) so that is why ports never get closed
* `PeerConnection.Close` should work can you try your test again with https://github.com/pion/webrtc/commit/a8c011e21d138b325735207c1fee341e3ca8d68c ?

I would love for you to get involved :) We are all available via [Slack](https://pion.ly/slack) if you want faster conversation also.

thanks!

**Comment by Sean-Der** [comment]
Hi @masterada 

I am going to close this for now since https://github.com/pion/webrtc/commit/a8c011e21d138b325735207c1fee341e3ca8d68c is in master.

If you are still having issues please re-open, and thank you for using Pion!
