### ISSUE TITLE
Any Video Documentation - How to Start?

### ISSUE THREAD

**Issue by StarMonk** [pion/webrtc#681]
Is there any Video Documentation - How to Start?

I have found some documentation here on how to start - https://pion.ly/knowledge-base/pion-basics/data-channels-introduction/

But any simple intro small video would be great to have more information on how to start quickly

**Comment by StarMonk** [comment]
any video documentation? I can not find anywhere.

**Comment by jinleileiking** [comment]
Try 11livechat or sfu minimal example

**Comment by jinleileiking** [comment]
Add welcome to slack

**Comment by Sean-Der** [comment]
Hey @StarMonk 

Yes we do need to add documentation around video examples! We have a couple video examples [here](https://github.com/pion/webrtc/tree/master/examples) and [here](https://github.com/pion/example-webrtc-applications)

And our [Slack](https://pion.ly/slack) is a great resource as well :) we would love to have you and can help 1:1

thanks for using Pion!

**Comment by PaulBGD** [comment]
So I was reading through this issue, I think he's talking about video tutorials on how to use the library instead of text tutorials. I could be reading this wrong though :)

**Comment by rebootcode** [comment]
Yes, he means "Video Tutorials on how to use the library"

**Comment by Sean-Der** [comment]
Closing for now since we don't have anything actionable.

I have given some talks on Pion you can see them on [siobud.com](https://siobud.com) but I don't have plans on making video tutorials currently.

If anyone is interested in making them I am available to answer questions about Pion/make the material compelling :)

thanks for using Pion!
