### ISSUE TITLE
how to using v2 in old golang version 

### ISSUE THREAD

**Issue by newzai** [pion/webrtc#710]
how to using v2 in golang version 1.10 or other not support go module version.

**Comment by daenney** [comment]
You can `git clone` it into your path, `cd` into it and then run a `go get ./...` to get all the dependencies. It's not ideal though.

With Go 1.10 going EOL soon since Go 1.13 is around the corner I'm not sure if it's still worth adding support for non-module enabled toolchains.

What is stopping you from upgrading to at least Go 1.11?

**Comment by Sean-Der** [comment]
Sorry @newzai I don't think we can support non-modules workflows. We are pretty strapped for dev time already, so this probably won't get developer attention.

I would love to see @daenney fix documented though! This is great solution, had no idea it was this easy.

Feel free to leave this open if you want to start a `FAQ.md` maybe with this solution? Otherwise we should probably resolve.

thanks for using Pion @newzai

**Comment by daenney** [comment]
The problem with my solution is that it doesn't respect dependency pinning. So doing the `go get ./...` approach will get the latest of what you don't have in your GOPATH yet and use what is there already for anything you've gotten before. You can get a bit closer with `go get -u ./...` which will update everything, but then that's not necessarily the versions of modules we've declared here. So though it could work it's probably prone to breakage and annoying to debug issues.

I can document it but I'm not sure we should as it would give the impression that's a flow we support, which I don't think we want to.

**Comment by Sean-Der** [comment]
Hey @newzai @daenney 

I started a FAQ [here](http://localhost:1313/knowledge-base/pion-basics/faq/#when-running-any-pion-webrtc-code-i-get-cannot-find-package-github-com-pion-webrtc-v2) 

there isn't anything we can do, but if you have any suggestions on updating the FAQ I would love to hear :)

**Comment by daenney** [comment]
Eh, your FAQ links to `http://localhost:1313/knowledge-base/pion-basics/faq/#when-running-any-pion-webrtc-code-i-get-cannot-find-package-github-com-pion-webrtc-v2`. Doesn't quite work :stuck_out_tongue:

**Comment by Sean-Der** [comment]
WORKS ON MACHINE.

@daenney fixed! thanks for catching that.
