### ISSUE TITLE
[Help] How to use it in LAN

### ISSUE THREAD

**Issue by StartAt24** [pion/webrtc#803]
I have a client get stream data (pictures) from the server.

But i don't have network. I just want to use it in localhost.

I have tried 
```	Go
config := webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{					
			},
		},
	}
```
But i cannot get the `RTCSessionDescription`.

How can i get it without IceServer?

By the way if i have a ICEServer. How to send big data through dataChannel?

I have got this panic `panic: Outbound packet larger than maximum message size 65535`. 
I'm using example: `data-channels-create`

**Comment by StartAt24** [comment]
@Sean-Der Thanks for your help. 
I have joined the Slack. 
I'll try to packetize my image.

**Comment by Sean-Der** [comment]
Hey @StartAt24!

Hopefully the new example is working out for you! https://github.com/pion/webrtc/tree/master/examples/data-channels-flow-control

Thank you for joining the Slack, your questions have caused us to improve stuff already so that is really awesome. I am going to close this issue now, but please feel free to open more with other issues if you think of them. thanks for using Pion!
