### ISSUE TITLE
support FEC for video stream?

### ISSUE THREAD

**Issue by 51ias** [pion/webrtc#920]
I'm using pion on the server to send video to chrome web client through webrtc. But I found out that the video was laggy when when there is slight packet loss. So I searched the code of pion and saw <b>no implementation of FEC in SRTP module</b>. 

Please let me know if any FEC (ulp fec or flex fec) will be supported in the future.
Or is there any mechanism of pion to perform better on a 1% packet loss network?

Thanks,

**Comment by adwpc** [comment]
https://github.com/pion/ion
Anti-Loss-Package 30%~50% with PLI and NACK.

**Comment by 51ias** [comment]
@adwpc Thanks for the quick reply. But the network between "client app" and ion node can't be trusted. Does WSS/SRTP work well on 1% packet loss network?

**Comment by 51ias** [comment]
Another thought: 
In PeerConnection::drainSRTP(), it reads rtcp packets but does nothing. Is this the place where  TransportLayerNack can be read and resend those lost RTP packets?

**Comment by Sean-Der** [comment]
Hey @51ias 

Sorry I took so long to respond, I do want to add `FEC` and other RTP resiliency features. The goal is to create a new package [RTPEngine](https://github.com/pion/webrtc/wiki/Big-Ideas#rtpengine) that does all this!

If you are interested in contributing I would love your help! I haven't had as much time as I had hoped, but I think it would be a great thing for someone to start on and then the excitement could pull others in.

I am going to close for now because it is on our roadmap, but there isn't anything immediately actionable. Thanks for using Pion (and bringing this up!)
